//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.
// Hand-written equivalent — no controller-gen in CI.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *VaultwardenSecretDataItem) DeepCopyInto(out *VaultwardenSecretDataItem) {
	*out = *in
}

// DeepCopy creates a deep copy of VaultwardenSecretDataItem.
func (in *VaultwardenSecretDataItem) DeepCopy() *VaultwardenSecretDataItem {
	if in == nil {
		return nil
	}
	out := new(VaultwardenSecretDataItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *VaultwardenSecretSpec) DeepCopyInto(out *VaultwardenSecretSpec) {
	*out = *in
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = make([]VaultwardenSecretDataItem, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy creates a deep copy of VaultwardenSecretSpec.
func (in *VaultwardenSecretSpec) DeepCopy() *VaultwardenSecretSpec {
	if in == nil {
		return nil
	}
	out := new(VaultwardenSecretSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *VaultwardenSecretStatus) DeepCopyInto(out *VaultwardenSecretStatus) {
	*out = *in
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a deep copy of VaultwardenSecretStatus.
func (in *VaultwardenSecretStatus) DeepCopy() *VaultwardenSecretStatus {
	if in == nil {
		return nil
	}
	out := new(VaultwardenSecretStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *VaultwardenSecret) DeepCopyInto(out *VaultwardenSecret) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy creates a deep copy of VaultwardenSecret.
func (in *VaultwardenSecret) DeepCopy() *VaultwardenSecret {
	if in == nil {
		return nil
	}
	out := new(VaultwardenSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements the runtime.Object interface.
func (in *VaultwardenSecret) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *VaultwardenSecretList) DeepCopyInto(out *VaultwardenSecretList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VaultwardenSecret, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a deep copy of VaultwardenSecretList.
func (in *VaultwardenSecretList) DeepCopy() *VaultwardenSecretList {
	if in == nil {
		return nil
	}
	out := new(VaultwardenSecretList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements the runtime.Object interface.
func (in *VaultwardenSecretList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
